import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'en'; // 'en', 'gu', or 'hi'

  String get currentLanguage => _currentLanguage;

  String get currentLanguageName {
    if (_currentLanguage == 'en') return 'English';
    if (_currentLanguage == 'hi') return 'हिन्दी';
    return 'ગુજરાતી';
  }

  void setLanguage(String langCode) {
    if (langCode == 'en' || langCode == 'gu' || langCode == 'hi') {
      _currentLanguage = langCode;
      notifyListeners();
    }
  }

  // Quick translate lookup map
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'mewad_bhavan': 'Mewad Bhavan',
      'palitana_dharamshala': 'Palitana Dharamshala',
      'book_a_room': 'Book a Room',
      'book_a_hall': 'Book a Hall',
      'notices': 'Notices',
      'contact': 'Contact',
      'latest_notices': 'Latest Notices',
      'our_rooms': 'Our Rooms',
      'upcoming_events': 'Upcoming Events',
      'view_all': 'View all',
      'jai_jinendra': 'Jai Jinendra',
      'book_your_stay': 'Book your stay',
      'explore_rooms': 'Explore rooms',
      'home': 'Home',
      'rooms': 'Rooms',
      'events': 'Events',
      'more': 'More',
      'reserve_your_stay': 'Reserve your stay',
      'about': 'About',
      'about_desc': 'Mewad Bhavan is a serene dharamshala in Palitana, Gujarat, serving devotees and pilgrims with comfortable rooms, halls and warm hospitality in the spirit of Jain tradition.',
      'quick_links': 'Quick Links',
      'my_bookings': 'My Bookings',
      'manager_dashboard': 'Manager Dashboard',
      'language': 'Language',
      'book_room': 'Book Room',
      'select_dates': 'Select Dates',
      'check_in': 'Check-in',
      'check_out': 'Check-out',
      'guest_details': 'Guest Details',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'number_of_guests': 'Number of Guests',
      'community': 'Community / Sect (optional)',
      'proceed_payment': 'Proceed to Payment',
      'book_event': 'Book for an Event',
      'event_desc': 'For group bookings, Sangh yatras & religious events',
      'event_type': 'Event type',
      'from_date': 'From date',
      'to_date': 'To date',
      'expected_guests': 'Expected guests',
      'notes': 'Notes (optional)',
      'request_booking': 'Request Booking',
      'manager': 'Manager',
      'whatsapp': 'WhatsApp',
      'phone': 'Phone Number',
      'email': 'Email',
      'address': 'Address',
      // Suffixes
      'per_night': 'per night',
      'night': 'night',
      'nights': 'nights',
      'guests': 'guests',
      'up_to': 'Up to',
      'available': 'available',
      'total': 'Total',
      'total_paid': 'Total Paid',
      'payment': 'Payment',
      'pay_now': 'Pay Now',
      'secure_payment': 'Secure Payment • 256-bit encrypted',
      'booking_confirmed': 'Booking Confirmed!',
      'success_desc': 'Your room has been successfully booked',
      'download_receipt': 'Download Receipt',
      'back_home': 'Back to Home',
      'payment_method': 'Payment Method',
      'receipt': 'Receipt',
      'receipt_downloaded': 'Receipt downloaded!',
      'no_bookings': 'No bookings yet',
      'enter_full_name': 'Enter your full name',
      'card': 'Card',
      'credit_debit_card': 'Credit / Debit Card',
      'net_banking': 'Net Banking',
      'all_major_banks': 'All major banks',
      'pay_at_counter': 'Pay at Counter',
      'cash_on_arrival': 'Cash on arrival',
      'booking_id': 'Booking ID',
      'guest': 'Guest',
      'duration': 'Duration',
      'payment_successful': 'Payment Successful',
      'no_bookings_desc': 'Your room bookings will appear here',
      'total_amount': 'Total Amount',
      'status_confirmed': 'Confirmed',
      'status_pending': 'Pending',
      'status_cancelled': 'Cancelled',
      // Dynamic strings maps
      // Rooms
      'r1_name': 'Standard Non-AC Room',
      'r1_desc': 'A comfortable non-AC room ideal for solo pilgrims or couples. Clean bedding, attached bathroom, and basic amenities.',
      'r2_name': 'Family Non-AC Room',
      'r2_desc': 'Spacious non-AC room for families with up to 4 guests. Two double beds, attached bathroom, and extra storage.',
      'r3_name': 'Deluxe AC Suite',
      'r3_desc': 'Premium air-conditioned suite with modern amenities, private balcony, and temple view. Best for families seeking comfort.',
      'r4_name': 'Dormitory',
      'r4_desc': 'Affordable shared dormitory with clean single beds. Ideal for solo pilgrims and group yatras. Common bathroom facilities.',
      'r5_name': 'AC Double Room',
      'r5_desc': 'Comfortable air-conditioned room with a double bed. Perfect for couples visiting Palitana for darshan.',
      // Amenities
      'Attached Bathroom': 'Attached Bathroom',
      'Clean Bedding': 'Clean Bedding',
      'Fan': 'Fan',
      'Hot Water': 'Hot Water',
      'Locker': 'Locker',
      'Two Beds': 'Two Beds',
      'Wardrobe': 'Wardrobe',
      'Sitting Area': 'Sitting Area',
      'AC': 'AC',
      'Balcony': 'Balcony',
      'Temple View': 'Temple View',
      'TV': 'TV',
      'Sofa': 'Sofa',
      'Single Bed': 'Single Bed',
      'Common Bathroom': 'Common Bathroom',
      'Double Bed': 'Double Bed',
      // Events
      'e1_title': 'Snatra Puja',
      'e1_loc': 'Main Hall',
      'e2_title': 'Pravachan by Acharya Shree',
      'e2_loc': 'Upashray',
      'e3_title': 'Chaumasa Begins',
      'e3_loc': 'Mewad Bhavan',
      'e4_title': 'Paryushana Parva',
      'e4_loc': 'Mewad Bhavan',
      'e5_title': 'Sangh Yatra from Ahmedabad',
      'e5_loc': 'Palitana Main Road',
      // Notices
      'n1_title': 'Chaumasa 2026 — Booking Open',
      'n1_desc': 'Bookings for Chaumasa stay (July–November) are now open. Early booking recommended.',
      'n2_title': 'Updhyan Tap — Limited Seats',
      'n2_desc': 'Updhyan tap aaradhana from 1 August. Register at the office or via this app.',
      'n3_title': 'Sangh from Mumbai arriving 20 June',
      'n3_desc': 'A sangh of 120 yatris will arrive on 20 June. Hall and rooms will be reserved.',
      'n4_title': 'New AC Rooms Available',
      'n4_desc': 'We have added 6 new AC rooms on the 2nd floor. Book now for summer comfort.',
      'n5_title': 'Water Conservation Drive',
      'n5_desc': 'We request all guests to use water wisely. The Dharamshala follows Jain principles of Aparigraha.',
      // General
      'main_hall': 'Main Hall — Mewad Bhavan',
      'request_received': 'Request Received!',
      'request_desc': 'Your event booking request has been submitted. The Dharamshala manager will review and confirm your booking shortly.',
      'got_it': 'Got it',
      'upcoming': 'Upcoming',
      'past': 'Past',
      'all': 'All',
      'no_notices': 'No notices found',
    },
    'gu': {
      'mewad_bhavan': 'મેવાડ ભવન',
      'palitana_dharamshala': 'પાલિતાણા ધર્મશાળા',
      'book_a_room': 'રૂમ બુક કરો',
      'book_a_hall': 'હોલ બુક કરો',
      'notices': 'સૂચનાઓ',
      'contact': 'સંપર્ક',
      'latest_notices': 'નવીનતમ સૂચનાઓ',
      'our_rooms': 'અમારા રૂમ',
      'upcoming_events': 'આવનારી ઇવેન્ટ્સ',
      'view_all': 'બધા જુઓ',
      'jai_jinendra': 'જય જિનેન્દ્ર',
      'book_your_stay': 'રોકાણ બુક કરો',
      'explore_rooms': 'રૂમ જુઓ',
      'home': 'હોમ',
      'rooms': 'રૂમ',
      'events': 'ઇવેન્ટ્સ',
      'more': 'વધુ',
      'reserve_your_stay': 'રોકાણ બુક કરો',
      'about': 'વિશે',
      'about_desc': 'મેવાડ ભવન એ પાલિતાણા, ગુજરાતમાં એક શાંત ધર્મશાળા છે, જે જૈન પરંપરાની ભાવનામાં આરામદાયક રૂમ, હોલ અને ભવ્ય આતિથ્ય સાથે ભક્તો અને યાત્રાળુઓની સેવા કરે છે.',
      'quick_links': 'ઝડપી લિંક્સ',
      'my_bookings': 'મારા બુકિંગ',
      'manager_dashboard': 'મેનેજર ડેશબોર્ડ',
      'language': 'ભાષા',
      'book_room': 'રૂમ બુક કરો',
      'select_dates': 'તારીખો પસંદ કરો',
      'check_in': 'ચેક-ઈન',
      'check_out': 'ચેક-આઉટ',
      'guest_details': 'મહેમાનની વિગતો',
      'full_name': 'પૂરું નામ',
      'phone_number': 'ફોન નંબર',
      'number_of_guests': 'મહેમાનોની સંખ્યા',
      'community': 'સમુદાય / પંથ (વૈકલ્પિક)',
      'proceed_payment': 'ચુકવણી કરવા આગળ વધો',
      'book_event': 'ઇવેન્ટ માટે બુક કરો',
      'event_desc': 'સંઘ યાત્રા, જૂથ બુકિંગ અને ધાર્મિક પ્રસંગો માટે',
      'event_type': 'પ્રસંગનો પ્રકાર',
      'from_date': 'શરૂઆતની તારીખ',
      'to_date': 'અંતિમ તારીખ',
      'expected_guests': 'અપેક્ષિત મહેમાનો',
      'notes': 'નોંધ (વૈકલ્પિક)',
      'request_booking': 'બુકિંગ વિનંતી કરો',
      'manager': 'મેનેજર',
      'whatsapp': 'વોટ્સએપ',
      'phone': 'ફોન નંબર',
      'email': 'ઇમેઇલ',
      'address': 'સરનામું',
      // Suffixes
      'per_night': 'રાત્રિ દીઠ',
      'night': 'રાત્રિ',
      'nights': 'રાત્રિઓ',
      'guests': 'મહેમાનો',
      'up_to': 'મહત્તમ',
      'available': 'ઉપલબ્ધ',
      'total': 'કુલ',
      'total_paid': 'કુલ ચુકવેલ',
      'payment': 'ચુકવણી',
      'pay_now': 'ચૂકવણી કરો',
      'secure_payment': 'સુરક્ષિત ચુકવણી • ૨૫૬-બીટ એન્ક્રિપ્ટેડ',
      'booking_confirmed': 'બુકિંગ કન્ફર્મ થયું!',
      'success_desc': 'તમારો રૂમ સફળતાપૂર્વક બુક થઈ ગયો છે',
      'download_receipt': 'રસીદ ડાઉનલોડ કરો',
      'back_home': 'હોમ પેજ પર પાછા ફરો',
      'payment_method': 'ચુકવણી પદ્ધતિ',
      'receipt': 'રસીદ',
      'receipt_downloaded': 'રસીદ ડાઉનલોડ થઈ ગઈ!',
      'no_bookings': 'હજી સુધી કોઈ બુકિંગ નથી',
      'enter_full_name': 'તમારું પૂરું નામ લખો',
      'card': 'કાર્ડ',
      'credit_debit_card': 'ક્રેડિટ / ડેબિટ કાર્ડ',
      'net_banking': 'નેટ બેંકિંગ',
      'all_major_banks': 'બધી મુખ્ય બેંકો',
      'pay_at_counter': 'કાઉન્ટર પર ચૂકવણી',
      'cash_on_arrival': 'આગમન પર રોકડ',
      'booking_id': 'બુકિંગ આઈડી',
      'guest': 'મહેમાન',
      'duration': 'સમયગાળો',
      'payment_successful': 'ચુકવણી સફળ રહી',
      'no_bookings_desc': 'તમારા રૂમ બુકિંગ અહીં દેખાશે',
      'total_amount': 'કુલ રકમ',
      'status_confirmed': 'કન્ફર્મ',
      'status_pending': 'બાકી',
      'status_cancelled': 'રદ કરેલ',
      // Dynamic strings maps
      // Rooms
      'r1_name': 'સ્ટાન્ડર્ડ નોન-એસી રૂમ',
      'r1_desc': 'એક આરામદાયક નોન-એસી રૂમ એકલા યાત્રાળુઓ અથવા યુગલો માટે યોગ્ય. સ્વચ્છ પથારી અને જોડાયેલ બાથરૂમ.',
      'r2_name': 'ફેમિલી નોન-એસી રૂમ',
      'r2_desc': '૪ મહેમાનો સુધીના પરિવારો માટે જગ્યા ધરાવતો નોન-એસી રૂમ. બે ડબલ બેડ અને જોડાયેલ બાથરૂમ.',
      'r3_name': 'ડિલોક્સ એસી સુઈટ',
      'r3_desc': 'આધુનિક સુવિધાઓ, ખાનગી બાલ્કની અને મંદિરના દૃશ્ય સાથે પ્રીમિયમ એર-કન્ડિશન્ડ રૂમ.',
      'r4_name': 'ધર્મશાળા ડોરમીટરી',
      'r4_desc': 'સ્વચ્છ સિંગલ બેડ સાથે સસ્તું સહિયારું રૂમ. એકલા યાત્રાળુઓ અને જૂથો માટે આદર્શ.',
      'r5_name': 'એસી ડબલ રૂમ',
      'r5_desc': 'ડબલ બેડ સાથે આરામદાયક એર-કન્ડિશન્ડ રૂમ. દર્શન માટે પાલિતાણા આવતા યુગલો માટે યોગ્ય.',
      // Amenities
      'Attached Bathroom': 'જોડાયેલ બાથરૂમ',
      'Clean Bedding': 'સ્વચ્છ પથારી',
      'Fan': 'પંખો',
      'Hot Water': 'ગરમ પાણી',
      'Locker': 'લોકર',
      'Two Beds': 'બે બેડ',
      'Wardrobe': 'કબાટ',
      'Sitting Area': 'બેસવાની જગ્યા',
      'AC': 'એસી',
      'Balcony': 'બાલ્કની',
      'Temple View': 'મંદિર વ્યુ',
      'TV': 'ટીવી',
      'Sofa': 'સોફા',
      'Single Bed': 'સિંગલ બેડ',
      'Common Bathroom': 'કોમન બાથરૂમ',
      'Double Bed': 'ડબલ બેડ',
      // Events
      'e1_title': 'સ્નાત્ર પૂજા',
      'e1_loc': 'મુખ્ય હોલ',
      'e2_title': 'આચાર્ય શ્રી દ્વારા પ્રવચન',
      'e2_loc': 'ઉપાશ્રય',
      'e3_title': 'ચૌમાસુ પ્રારંભ',
      'e3_loc': 'મેવાડ ભવન',
      'e4_title': 'પર્યુષણ પર્વ',
      'e4_loc': 'મેવાડ ભવન',
      'e5_title': 'અમદાવાદથી સંઘ યાત્રા',
      'e5_loc': 'પાલિતાણા મુખ્ય માર્ગ',
      // Notices
      'n1_title': 'ચૌમાસા ૨૦૨૬ — બુકિંગ ચાલુ',
      'n1_desc': 'ચૌમાસા રોકાણ માટે બુકિંગ (જુલાઈ-નવેમ્બર) હવે ખુલ્લું છે. વહેલા બુકિંગની ભલામણ કરાય છે.',
      'n2_title': 'ઉપધાન તપ — મર્યાદિત બેઠકો',
      'n2_desc': '૧ ઓગસ્ટથી ઉપધાન તપ આરાધના શરૂ થશે. કાર્યાલય અથવા આ એપ્લિકેશન દ્વારા નોંધણી કરો.',
      'n3_title': 'મુંબઈથી સંઘનું આગમન ૨૦ જૂન',
      'n3_desc': '૧૨૦ યાત્રાળુઓનો સંઘ ૨૦ જૂને પહોંચશે. હોલ અને રૂમ અનામત રાખવામાં આવશે.',
      'n4_title': 'નવા એસી રૂમ ઉપલબ્ધ',
      'n4_desc': 'બીજા માળે ૬ નવા એસી રૂમ ઉમેરવામાં આવ્યા છે. ઉનાળાના આરામ માટે હમણાં જ બુક કરો.',
      'n5_title': 'પાણી બચાવો અભિયાન',
      'n5_desc': 'અમે બધા મહેમાનોને પાણીનો સમજદારીપૂર્વક ઉપયોગ કરવા વિનંતી કરીએ છીએ.',
      // General
      'main_hall': 'મુખ્ય હોલ — મેવાડ ભવન',
      'request_received': 'વિનંતી પ્રાપ્ત થઈ!',
      'request_desc': 'તમારી ઇવેન્ટ બુકિંગ વિનંતી સબમિટ કરવામાં આવી છે. ધર્મશાળા મેનેજર ટૂંક સમયમાં સમીક્ષા કરીને કન્ફર્મ કરશે.',
      'got_it': 'સમજાયું',
      'upcoming': 'આવનારા પ્રસંગો',
      'past': 'ભૂતકાળના પ્રસંગો',
      'all': 'બધા',
      'no_notices': 'કોઈ સૂચનાઓ મળી નથી',
    },
    'hi': {
      'mewad_bhavan': 'मेवाड़ भवन',
      'palitana_dharamshala': 'पालीताणा धर्मशाला',
      'book_a_room': 'कमरा बुक करें',
      'book_a_hall': 'हॉल बुक करें',
      'notices': 'सूचनाएं',
      'contact': 'संपर्क',
      'latest_notices': 'नवीनतम सूचनाएं',
      'our_rooms': 'हमारे कमरे',
      'upcoming_events': 'आने वाले कार्यक्रम',
      'view_all': 'सभी देखें',
      'jai_jinendra': 'जय जिनेन्द्र',
      'book_your_stay': 'अपना प्रवास बुक करें',
      'explore_rooms': 'कमरे देखें',
      'home': 'होम',
      'rooms': 'कमरे',
      'events': 'कार्यक्रम',
      'more': 'अधिक',
      'reserve_your_stay': 'अपना प्रवास सुरक्षित करें',
      'about': 'हमारे बारे में',
      'about_desc': 'मेवाड़ भवन पालीताणा, गुजरात में एक शांत धर्मशाला है, जो जैन परंपरा की भावना में आरामदायक कमरों, हॉलों और गर्मजोशी से भरे आतिथ्य के साथ भक्तों और तीर्थयात्रियों की सेवा करती है।',
      'quick_links': 'त्वरित संपर्क',
      'my_bookings': 'मेरी बुकिंग',
      'manager_dashboard': 'मैनेजर डैशबोर्ड',
      'language': 'भाषा',
      'book_room': 'कमरा बुक करें',
      'select_dates': 'तिथियां चुनें',
      'check_in': 'चेक-इन',
      'check_out': 'चेक-आउट',
      'guest_details': 'अतिथि का विवरण',
      'full_name': 'पूरा नाम',
      'phone_number': 'फ़ोन नंबर',
      'number_of_guests': 'अतिथियों की संख्या',
      'community': 'समुदाय / पंथ (वैकल्पिक)',
      'proceed_payment': 'भुगतान के लिए आगे बढ़ें',
      'book_event': 'कार्यक्रम के लिए बुक करें',
      'event_desc': 'समूह बुकिंग, संघ यात्रा और धार्मिक कार्यक्रमों के लिए',
      'event_type': 'कार्यक्रम का प्रकार',
      'from_date': 'प्रारंभ तिथि',
      'to_date': 'अंतिम तिथि',
      'expected_guests': 'अपेक्षित अतिथि',
      'notes': 'टिप्पणी (वैकल्पिक)',
      'request_booking': 'बुकिंग का अनुरोध करें',
      'manager': 'मैनेजर',
      'whatsapp': 'व्हाट्सएप',
      'phone': 'फ़ोन नंबर',
      'email': 'ईमेल',
      'address': 'पता',
      // Suffixes
      'per_night': 'प्रति रात',
      'night': 'रात',
      'nights': 'रातें',
      'guests': 'अतिथि',
      'up_to': 'अधिकतम',
      'available': 'उपलब्ध',
      'total': 'कुल',
      'total_paid': 'कुल भुगतान',
      'payment': 'भुगतान',
      'pay_now': 'अभी भुगतान करें',
      'secure_payment': 'सुरक्षित भुगतान • 256-बिट एन्क्रिप्टेड',
      'booking_confirmed': 'बुकिंग की पुष्टि हो गई!',
      'success_desc': 'आपका कमरा सफलतापूर्वक बुक कर लिया गया है',
      'download_receipt': 'रसीद डाउनलोड करें',
      'back_home': 'होम पर वापस जाएं',
      'payment_method': 'भुगतान विधि',
      'receipt': 'रसीद',
      'receipt_downloaded': 'रसीद डाउनलोड हो गई!',
      'no_bookings': 'अभी तक कोई बुकिंग नहीं',
      'enter_full_name': 'अपना पूरा नाम दर्ज करें',
      'card': 'कार्ड',
      'credit_debit_card': 'क्रेडिट / डेबिट कार्ड',
      'net_banking': 'नेट बैंकिंग',
      'all_major_banks': 'सभी प्रमुख बैंक',
      'pay_at_counter': 'काउंटर पर भुगतान',
      'cash_on_arrival': 'आगमन पर नकद',
      'booking_id': 'बुकिंग आईडी',
      'guest': 'अतिथि',
      'duration': 'अवधि',
      'payment_successful': 'भुगतान सफल रहा',
      'no_bookings_desc': 'आपकी कमरे की बुकिंग यहाँ दिखाई देगी',
      'total_amount': 'कुल राशि',
      'status_confirmed': 'पुष्टि की गई',
      'status_pending': 'लंबित',
      'status_cancelled': 'रद्द',
      // Dynamic strings maps
      // Rooms
      'r1_name': 'मानक नॉन-एसी कमरा',
      'r1_desc': 'एक आरामदायक नॉन-एसी कमरा जो अकेले तीर्थयात्रियों या जोड़ों के लिए आदर्श है। साफ बिस्तर, संलग्न शौचालय और बुनियादी सुविधाएं।',
      'r2_name': 'पारिवारिक नॉन-एसी कमरा',
      'r2_desc': '4 अतिथियों तक के परिवारों के लिए विशाल नॉन-एसी कमरा। दो डबल बेड, संलग्न शौचालय और अतिरिक्त अलमारी।',
      'r3_name': 'डीलक्स एसी सुइट',
      'r3_desc': 'आधुनिक सुविधाओं, निजी बालकनी और मंदिर के दृश्य के साथ प्रीमियम वातानुकूलित सुइट। आराम की तलाश करने वाले परिवारों के लिए सर्वश्रेष्ठ।',
      'r4_name': 'धर्मशाला डॉरमेट्री',
      'r4_desc': 'साफ सिंगल बेड के साथ किफायती साझा डॉरमेट्री। अकेले तीर्थयात्रियों और समूह यात्राओं के लिए आदर्श। साझा शौचालय सुविधाएं।',
      'r5_name': 'एसी डबल रूम',
      'r5_desc': 'डबल बेड के साथ आरामदायक वातानुकूलित कमरा। दर्शन के लिए पालीताणा आने वाले जोड़ों के लिए बिल्कुल सही।',
      // Amenities
      'Attached Bathroom': 'संलग्न शौचालय',
      'Clean Bedding': 'साफ बिस्तर',
      'Fan': 'पंखा',
      'Hot Water': 'गर्म पानी',
      'Locker': 'लॉकर',
      'Two Beds': 'दो बेड',
      'Wardrobe': 'अलमारी',
      'Sitting Area': 'बैठने की जगह',
      'AC': 'एसी',
      'Balcony': 'बालकनी',
      'Temple View': 'मंदिर दृश्य',
      'TV': 'टीवी',
      'Sofa': 'सोफा',
      'Single Bed': 'सिंगल बेड',
      'Common Bathroom': 'साझा शौचालय',
      'Double Bed': 'डबल बेड',
      // Events
      'e1_title': 'स्नात्र पूजा',
      'e1_loc': 'मुख्य हॉल',
      'e2_title': 'आचार्य श्री द्वारा प्रवचन',
      'e2_loc': 'उपाश्रय',
      'e3_title': 'चौमासा प्रारंभ',
      'e3_loc': 'मेवाड़ भवन',
      'e4_title': 'पर्युषण पर्व',
      'e4_loc': 'मेवाड़ भवन',
      'e5_title': 'अहमदाबाद से संघ यात्रा',
      'e5_loc': 'पालीताणा मुख्य मार्ग',
      // Notices
      'n1_title': 'चौमासा 2026 — बुकिंग शुरू',
      'n1_desc': 'चौमासा प्रवास (जुलाई-नवंबर) के लिए बुकिंग अब खुली है। शीघ्र बुकिंग की अनुशंसा की जाती है।',
      'n2_title': 'उपधान तप — सीमित सीटें',
      'n2_desc': '1 अगस्त से उपधान तप आराधना। कार्यालय में या इस ऐप के माध्यम से पंजीकरण करें।',
      'n3_title': 'मुंबई से संघ का आगमन 20 जून',
      'n3_desc': '120 यात्रियों का एक संघ 20 जून को पहुंचेगा। हॉल और कमरे आरक्षित रहेंगे।',
      'n4_title': 'नए एसी कमरे उपलब्ध',
      'n4_desc': 'हमने दूसरी मंजिल पर 6 नए एसी कमरे जोड़े हैं। गर्मियों में आराम के लिए अभी बुक करें।',
      'n5_title': 'जल संरक्षण अभियान',
      'n5_desc': 'हम सभी मेहमानों से पानी का विवेकपूर्ण उपयोग करने का अनुरोध करते हैं। धर्मशाला अपरिग्रह के जैन सिद्धांतों का पालन करती है।',
      // General
      'main_hall': 'मुख्य हॉल — मेवाड़ भवन',
      'request_received': 'अनुरोध प्राप्त हुआ!',
      'request_desc': 'आपका इवेंट बुकिंग अनुरोध सबमिट कर दिया गया है। धर्मशाला प्रबंधक जल्द ही आपकी बुकिंग की समीक्षा और पुष्टि करेंगे।',
      'got_it': 'समझ गए',
      'upcoming': 'आगामी',
      'past': 'विगत',
      'all': 'सभी',
      'no_notices': 'कोई सूचना नहीं मिली',
    }
  };

  String translate(String key) {
    return _localizedValues[_currentLanguage]?[key] ?? key;
  }
}

